### ISSUE TITLE
Segmentation Fault while make

### ISSUE THREAD

**Issue by EricTtTtT** [nimish15shah/GRAPHOPT#3]
Hi, I created a docker for Centos8 and installed or-tools, packages in requirement.txt. But there's a Segmentation Fault.  Are there other things need to do before running?

The following is the output of make.

[root@6b8e3c635d7e GRAPHOPT]# make
python main.py --tmode full --net mnist --threads 2 --cir_type psdd
/usr/local/lib/python3.8/site-packages/networkx/__init__.py
/usr/local/lib/python3.8/site-packages/minizinc/__init__.py:26: RuntimeWarning: MiniZinc was not found on the system. No default driver could be initialised.
  warnings.warn(
total_nodes:  0 , leaf_nodes:  0 , arith_nodes:  0
2023-04-12 10:36:34,887,887 INFO     [graph_analysis.py:108] ###### Target workload: mnist, Target threads: 2 ######
2023-04-12 10:36:34,977,977 INFO     [psdd.py:30] raw graph len: 12777
2023-04-12 10:36:35,052,52 INFO     [psdd.py:37] binarized graph len: 15784
2023-04-12 10:36:35,127,127 INFO     [psdd.py:46] Leaf nodes: 5370
2023-04-12 10:36:35,347,347 INFO     [graph_init.py:76] Critical path length: 26
2023-04-12 10:36:35,349,349 INFO     [graph_analysis.py:159] ####### Generating superlayers #######
2023-04-12 10:36:35,349,349 WARNING  [graph_analysis.py:285] Writing partitions to files
2023-04-12 10:36:35,767,767 INFO     [partition.py:475] Max level: 25
2023-04-12 10:36:35,767,767 INFO     [partition.py:476] Total nodes: 15784
2023-04-12 10:36:35,767,767 INFO     [partition.py:477] Total number of layers: 26
2023-04-12 10:36:35,768,768 INFO     [partition.py:478] nodes_on_each_layer: [8, 64, 220, 478, 816, 1120, 1325, 1351, 1268, 1113, 874, 634, 423, 270, 164, 100, 60, 41, 27, 20, 15, 10, 6, 4, 2, 1]
2023-04-12 10:36:35,793,793 INFO     [minizinc_top.py:264] Using 64 CPU threads for executing Google OR-Tools solver
 Using 64 CPU threads for executing Google OR-Tools solver 
 Trying to map 10128 nodes to 2 threads 
2023-04-12 10:36:36,178,178 INFO     [minizinc_top.py:324] Total mapping to curr super layer: nodes: 8468, operations: 8468
2023-04-12 10:36:36,178,178 INFO     [minizinc_top.py:334] Total nodes mapped to superlayers so far: [8468]. Nodes yet to be mapped: 1946
 A superlayer is generated 
 Trying to map 1946 nodes to 2 threads 
2023-04-12 10:36:36,434,434 INFO     [minizinc_top.py:324] Total mapping to curr super layer: nodes: 1568, operations: 1568
2023-04-12 10:36:36,434,434 INFO     [minizinc_top.py:334] Total nodes mapped to superlayers so far: [8468, 1568]. Nodes yet to be mapped: 378
 A superlayer is generated 
 Trying to map 378 nodes to 2 threads 
2023-04-12 10:36:36,570,570 INFO     [minizinc_top.py:324] Total mapping to curr super layer: nodes: 363, operations: 363
2023-04-12 10:36:36,570,570 INFO     [minizinc_top.py:334] Total nodes mapped to superlayers so far: [8468, 1568, 363]. Nodes yet to be mapped: 15
 A superlayer is generated 
 Trying to map 15 nodes to 2 threads 
2023-04-12 10:36:36,572,572 INFO     [minizinc_top.py:324] Total mapping to curr super layer: nodes: 15, operations: 15
2023-04-12 10:36:36,572,572 INFO     [minizinc_top.py:334] Total nodes mapped to superlayers so far: [8468, 1568, 363, 15]. Nodes yet to be mapped: 0
 A superlayer is generated 
2023-04-12 10:36:36,572,572 INFO     [minizinc_top.py:349] Total super layers: 4
2023-04-12 10:36:36,572,572 INFO     [minizinc_top.py:350] Nodes mapped to individual super layers: [8468, 1568, 363, 15]
2023-04-12 10:36:36,586,586 INFO     [graph_analysis.py:296] edge_crossing : 431
2023-04-12 10:36:36,586,586 WARNING  [graph_analysis.py:309] Writing partitions to files at ./no_backup/superlayers/mnist_TWO_WAY_PARTITION_TWO_WAY_LIMIT_LAYERS_CPU_FINE_2.p
2023-04-12 10:36:36,598,598 INFO     [partition.py:857] layers before combining: 4
2023-04-12 10:36:36,599,599 INFO     [partition.py:884] list_of_combined_layer_list: [[0], [1, 2, 3]]
2023-04-12 10:36:36,599,599 INFO     [partition.py:914] layers after combining: 2
2023-04-12 10:36:36,599,599 INFO     [graph_analysis.py:165] ####### Generating OpenMP code #######
2023-04-12 10:36:37,773,773 INFO     [gen_code.py:722] writing openmp global variables to file: ./no_backup/openmp/mnist_TWO_WAY_PARTITION_TWO_WAY_LIMIT_LAYERS_CPU_FINE_2.c
2023-04-12 10:36:37,773,773 INFO     [graph_analysis.py:185] ####### Executing parallelized DAG #######
2023-04-12 10:36:37,773,773 INFO     [graph_analysis.py:187] Logging results in ./log/run_log_openmp file
make[1]: Entering directory '/GRAPHOPT/src/openmp'
export KMP_AFFINITY=verbose # for threading information
export MKL_NUM_THREADS=24
export OMP_NUM_THREADS=24
export KMP_AFFINITY=granularity=fine,compact,1,0
make[1]: Leaving directory '/GRAPHOPT/src/openmp'
2023-04-12 10:36:37,789,789 INFO     [graph_analysis.py:493] Modifying main openmp file: ./src/openmp/par_for_v2.cpp to include the header file ..\/..\/.\/no_backup\/openmp\/mnist_TWO_WAY_PARTITION_TWO_WAY_LIMIT_LAYERS_CPU_FINE_2.c
sed -i '8s/.*/#include "..\/..\/.\/no_backup\/openmp\/mnist_TWO_WAY_PARTITION_TWO_WAY_LIMIT_LAYERS_CPU_FINE_2.c"/' ./src/openmp/par_for_v2.cpp
make[1]: Entering directory '/GRAPHOPT/src/openmp'
g++ -std=c++11 -fopenmp -march=native -Ofast -fassociative-math  par_for_v2.cpp -o par_for_v2
par_for_v2.cpp: In function ‘int par_for(int, int, int, int, const int*, int, const int*, float*, const bool*, const int*, const int*)’:
par_for_v2.cpp:54:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
make[1]: Leaving directory '/GRAPHOPT/src/openmp'
2023-04-12 10:36:37,938,938 INFO     [graph_analysis.py:502] Excuting 10k iterations of parallel code...
make[1]: *** [Makefile:21: run_psdd] Segmentation fault (core dumped)
Traceback (most recent call last):
  File "main.py", line 130, in <module>
    sys.exit(main())
  File "main.py", line 127, in main
    run(args)
  File "main.py", line 19, in run
    analysis_obj.test(args)
  File "/GRAPHOPT/graph_analysis.py", line 194, in test
    par_for_psdd([args.net], [args.threads], log_path, "../../" + self.global_var.OPENMP_PATH, suffix)
  File "/GRAPHOPT/graph_analysis.py", line 504, in par_for_psdd
    output= subprocess.check_output(cmd, shell=True)
  File "/usr/lib64/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cd src/openmp; make run_psdd' returned non-zero exit status 2.
make: *** [Makefile:5: psdd_sample] Error 1

**Comment by nimish15shah** [comment]
Hi Eric,

All the steps seem to be working properly, except the OpenMP multi-threaded execution at the end. 
Could you please share the following file:
GRAPHOPT/no_backup/openmp/mnist_TWO_WAY_PARTITION_TWO_WAY_LIMIT_LAYERS_CPU_FINE_2.c

Kind regards,
Nimish

**Comment by EricTtTtT** [comment]
Hi Nimish,

Thanks for your prompt reply.  The file is attached. (change to .txt for upload)
[mnist_TWO_WAY_PARTITION_TWO_WAY_LIMIT_LAYERS_CPU_FINE_2.txt](https://github.com/nimish15shah/GRAPHOPT/files/11213561/mnist_TWO_WAY_PARTITION_TWO_WAY_LIMIT_LAYERS_CPU_FINE_2.txt)

**Comment by nimish15shah** [comment]
Hi Eric,

The file looks normal, but I do not have the setup at the moment to verify it properly.
Could you please try `make sptrsv_sample` or `make all` to see if the other workloads also face the same issue?

**Comment by EricTtTtT** [comment]
I tried both make sptrsv_sample and make all. The output logs are the same as the previous ones. There is no Segmentation Fault. However, the program seems to be stuck here

INFO     [graph_analysis.py:468] Excuting 1k iterations of parallel code...

How long will it usually take?  It runs for almost ten hour and still no result. I check that CPU keeps running par_for_sparse

![image](https://user-images.githubusercontent.com/52962174/231955161-ff1aadd1-b135-4070-87d9-affee52cb65c.png)

**Comment by EricTtTtT** [comment]
I reinstall minizinc and the problem is solved.  Thanks!
